build:
  binary: "lavad"
  main: "cmd/lavad"
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: user1
    coins: ["10000token", "200000000stake"]
  - name: user2
    coins: ["10000token", "200000000stake"]
  - name: user3
    coins: ["10000token", "200000000stake"]
  - name: servicer1
    coins: ["10000token", "200000000stake"]
  - name: servicer2
    coins: ["10000token", "200000000stake"]
  - name: servicer3
    coins: ["10000token", "200000000stake"]
  - name: servicer4
    coins: ["10000token", "200000000stake"]
  - name: servicer5
    coins: ["10000token", "200000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  chain_id: "lava"
  app_state:
    gov:
      voting_params:
        voting_period: "20s"