max-provider-latency: 150ms
subscription-days-left-alert: 10
interval: 5s
allowed_time_lag: 30s
query-retries: 5
identifier: health_example
cu-percent-threshold: 0.2
alert-suppression-interval: 60s
disable-alert-suppression: false
suppression-alert-count-threshold: 2
metrics-listen-address: ":7776"
disable-alert-logging: false
allow-insecure-provider-dialing: true
consumer_endpoints:
  - chain-id: ETH1
    api-interface: jsonrpc
    network-address: http://127.0.0.1:3333
    addons:
      - debug
  - chain-id: LAV1
    api-interface: rest
    network-address: http://127.0.0.1:3360
  - chain-id: LAV1
    api-interface: tendermintrpc
    network-address: http://127.0.0.1:3361
  - chain-id: LAV1
    api-interface: grpc
    network-address: 127.0.0.1:3362
#REPLACED
subscription_addresses:
provider_addresses:
