max-provider-latency: 150ms
interval: 0s
allowed_time_lag: 30s
query-retries: 5
identifier: health_all_providers
disable-alert-suppression: false
suppression-alert-count-threshold: 0
metrics-listen-address: ":7776"
disable-alert-logging: false
post-results-address: http://127.0.0.1:6500
provider_addresses:
  - all 

