endpoints:
    - api-interface: jsonrpc
      chain-id: ETH1
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: my-eth-node.com/eth/ws/archive
          addons:
            - archive
        - url: my-eth-node.com/eth-with-debug/ws
          addons:
            - debug