endpoints:
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: "0.0.0.0:2220"
      node-urls:
        - url: ws://0.0.0.0:26657/websocket
        - url: http://0.0.0.0:26657
    - api-interface: grpc
      chain-id: LAV1
      network-address:
        address: "0.0.0.0:2220"
      node-urls: 
        - url: 0.0.0.0:9090
    - api-interface: rest
      chain-id: LAV1
      network-address:
        address: "0.0.0.0:2220"
      node-urls: 
        - url: http://0.0.0.0:1317
