endpoints:
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address: 127.0.0.1:2221
      node-urls:
        - url: ws://127.0.0.1:26657/websocket
          auth-config:
            auth-query: auth=xyz
            auth-headers:
              AUTH-X-HEADER: xyz
        - url: http://127.0.0.1:26657
          auth-config:
            auth-query: auth=xxyyzz
            auth-headers:
              AUTH-X-HEADER-2: xxyyzz
    - api-interface: grpc
      chain-id: LAV1
      network-address: 127.0.0.1:2221
      node-urls: 
        url: 127.0.0.1:9090
    - api-interface: rest
      chain-id: LAV1
      network-address: 127.0.0.1:2221
      node-urls: 
        - url: http://127.0.0.1:1317
          auth-config:
            auth-query: auth=banana
            auth-headers:
              AUTH-X-HEADER-2: xxyyzz
    - api-interface: jsonrpc
      chain-id: ETH1
      network-address: 127.0.0.1:2221
      node-urls: 
        - url: wss://ethereum-rpc.com/ws/
          auth-config:
            auth-query: auth=banana
            auth-headers:
              AUTH-X-HEADER-2: xxyyzz