endpoints:
    - api-interface: rest
      chain-id: MORALIS
      network-address:
        address: "127.0.0.1:2221"
      node-urls:
        - url: "https://deep-index.moralis.io/api/v2.2"
          auth-config:
              auth-headers:
                X-API-Key: <YOUR_API_KEY>
                accept: application/json