version: '3.9'

x-vol:
  - &vol-lava
    ${LAVA_HOME_DIR:-.lava}:/lava/.lava

services:

  lava-node:
    build: ..
    image: lava:latest
    command: "node"
    environment:
      # common env
      - LAVA_LISTEN_IP=${LAVA_LISTEN_IP:-0.0.0.0}
      - LAVA_LOG_LEVEL=${LAVA_LOG_LEVEL:-info}
    ports:
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_API:-1317}:1317'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_GRPC:-9090}:9090'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_GRPC_WEB:-9091}:9091'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_P2P:-26656}:26656'
      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_NODE_PORT_RPC:-26657}:26657'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: on-failure:5
    profiles: ["node"]

# --- OUTDATED ---
#  lava-portal:
#    build: ..
#    image: lava:latest
#    command: "portal"
#    volumes:
#      - *vol-lava
#    environment:
#      # common env
#      - LAVA_LISTEN_IP=${LAVA_LISTEN_IP:-0.0.0.0}
#      - LAVA_LOG_LEVEL=${LAVA_LOG_LEVEL:-info}
#      # portal env
#      - LAVA_USER
#      - LAVA_KEYRING
#      - LAVA_ADDRESS
#      - LAVA_STAKE_AMOUNT
#      - LAVA_GAS_MODE
#      - LAVA_GAS_ADJUST
#      - LAVA_GAS_PRICE
#      - LAVA_GEOLOCATION
#      - LAVA_RPC_NODE
#      - LAVA_CHAIN_ID
#      - LAVA_RELAY_CHAIN_ID
#      - LAVA_RELAY_IFACE
#      - LAVA_PORTAL_PORT
#    ports:
#      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_PORTAL_PORT:-8080}:${LAVA_PORTAL_PORT:-8080}'
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: '2gb'
#    restart: on-failure:5
#    profiles: ["portal"]

# --- OUTDATED ---
#  lava-provider:
#    build: ..
#    image: lava:latest
#    command: "provider"
#    volumes:
#      - *vol-lava
#    environment:
#      # common env
#      - LAVA_LISTEN_IP=${LAVA_LISTEN_IP:-0.0.0.0}
#      - LAVA_LOG_LEVEL=${LAVA_LOG_LEVEL:-info}
#      # portal env
#      - LAVA_USER
#      - LAVA_KEYRING
#      - LAVA_ADDRESS
#      - LAVA_STAKE_AMOUNT
#      - LAVA_GAS_MODE
#      - LAVA_GAS_ADJUST
#      - LAVA_GAS_PRICE
#      - LAVA_GEOLOCATION
#      - LAVA_RPC_NODE
#      - LAVA_CHAIN_ID
#      - LAVA_RELAY_ENDPOINT
#      - LAVA_RELAY_NODE_URL
#      - LAVA_RELAY_CHAIN_ID
#      - LAVA_RELAY_IFACE
#      - LAVA_PORTAL_PORT
#    ports:
#      - '${LAVA_LISTEN_IP:-0.0.0.0}:${LAVA_PORTAL_PORT:-8080}:${LAVA_PORTAL_PORT:-8080}'
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: '4gb'
#    restart: on-failure:5
#    profiles: ["provider"]
