endpoints:
# if you do not have a non archive node, you can set the non archive endpoint to the archive node (yet route to it regular queries, that do not pay the multiplier)
    - api-interface: jsonrpc
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: evmos/rpc/archive
          addons:
            - archive
        - url: evmos/rpc
    - api-interface: rest
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: /evmos/rest/archive
          addons:
            - archive
        - url: /evmos/rest
    - api-interface: grpc
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: evmos-grpc-secure-archive:443
          auth-config:
            use-tls: true 
          addons:
            - archive
        - url: evmos-grpc-secure:443
          auth-config:
            use-tls: true 
    - api-interface: tendermintrpc
      chain-id: EVMOS
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: evmos/tendermint-rpc-http-archive
          addons:
            - archive
        - url: evmos/tendermint-rpc-ws-archive
          addons:
            - archive
        - url: evmos/tendermint-rpc-http
        - url: evmos/tendermint-rpc-ws