endpoints:
    - api-interface: tendermintrpc
      chain-id: INDEX_RELACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls:
        - url: RELACE_THIS_URL
        - url: RELACE_THIS_URL
    - api-interface: grpc
      chain-id: INDEX_RELACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: RELACE_THIS_URL
    - api-interface: rest
      chain-id: INDEX_RELACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: RELACE_THIS_URL
    - api-interface: jsonrpc
      chain-id: INDEX_RELACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: RELACE_THIS_URL
