endpoints:
    - chain-id: EVMOS
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3333
    - chain-id: EVMOS
      api-interface: rest
      network-address: 127.0.0.1:3334
    - chain-id: EVMOS
      api-interface: grpc
      network-address: 127.0.0.1:3335
    - chain-id: EVMOS
      api-interface: jsonrpc
      network-address: 127.0.0.1:3336
metrics-listen-address: ":7779"