endpoints:
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address: 127.0.0.1:2221
      node-url:
        - ws://127.0.0.1:26657/websocket
        - http://127.0.0.1:26657
    - api-interface: grpc
      chain-id: LAV1
      network-address: 127.0.0.1:2221
      node-url: 127.0.0.1:9090
    - api-interface: rest
      chain-id: LAV1
      network-address: 127.0.0.1:2221
      node-url: http://127.0.0.1:1317
    # - api-interface: jsonrpc
    #   chain-id: ETH1
    #   network-address: 127.0.0.1:2221
    #   node-url: wss://ethereum-rpc.com/ws/