endpoints:
  - chain-id: ETH1
    api-interface: jsonrpc
    network-address: 127.0.0.1:3333
  - chain-id: LAV1
    api-interface: rest
    network-address: 127.0.0.1:3360
  - chain-id: LAV1
    api-interface: tendermintrpc
    network-address: 127.0.0.1:3361
  - chain-id: LAV1
    api-interface: grpc
    network-address: 127.0.0.1:3362
metrics-listen-address: ":7779"
# referer-be-address: "http://127.0.0.1:6500"
# reports-be-address: "http://127.0.0.1:6501"
