endpoints:
  - chain-id: LAV1
    api-interface: rest
    network-address: 127.0.0.1:3363
  - chain-id: LAV1
    api-interface: tendermintrpc
    network-address: 127.0.0.1:3364
  - chain-id: LAV1
    api-interface: grpc
    network-address: 127.0.0.1:3365
metrics-listen-address: ":7780"
# referer-be-address: "http://127.0.0.1:6500"
# reports-be-address: "http://127.0.0.1:6501"
