name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        binary: [lavad, lavap, lavavisor]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.5

      - name: Run GoReleaser
        id: releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --single-target --snapshot --clean
          workdir: cmd/${{ matrix.binary }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}