name: Lava Consensus Tests

on: [pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.5
    

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    ######################################################
    ### Run Consensus unitests
    ######################################################
    - name: lavad cli test
      run: |
        chmod +x cli_test.sh
        ./scripts/cli_test.sh         

    - name: lava utils unit Tests
      run: go test ./utils/...

    - name: lava common unit Tests
      run: go test ./common/...

    - name: lava pairing unit Tests
      run: go test ./x/pairing/...
      
    - name: lava epochstorage unit Tests
      run: go test ./x/epochstorage/...

    - name: lava spec unit Tests
      run: go test ./x/spec/...

    - name: lava conflict unit Tests
      run: go test ./x/conflict/...

    - name: lava plans unit Tests
      run: go test ./x/plans/...

    - name: lava projects unit Tests
      run: go test ./x/projects/... 

    - name: lava subscription unit Tests
      run: go test ./x/subscription/... 
