name: Lava Consensus Tests

on: 
  pull_request

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.20.5
    

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    ######################################################
    ### Run Consensus unitests
    ######################################################
    - name: Lava Unit Tests
      run: |
        go install github.com/jstemmer/go-junit-report/v2@latest
        go test -v ./utils/... | go-junit-report -iocopy -set-exit-code > utils-report.xml  
        go test -v ./common/... | go-junit-report -iocopy -set-exit-code > common-report.xml  
        go test -v ./x/pairing/... | go-junit-report -iocopy -set-exit-code > pairing-report.xml  
        go test -v ./x/epochstorage/... | go-junit-report -iocopy -set-exit-code > epochstorage-report.xml  
        go test -v ./x/spec/... | go-junit-report -iocopy -set-exit-code > spec-report.xml  
        go test -v ./x/conflict/... | go-junit-report -iocopy -set-exit-code > conflict-report.xml  
        go test -v ./x/plans/... | go-junit-report -iocopy -set-exit-code > plans-report.xml  
        go test -v ./x/projects/... | go-junit-report -iocopy -set-exit-code > projects-report.xml  
        go test -v ./x/subscription/... | go-junit-report -iocopy -set-exit-code > subscription-report.xml  
        go test -v ./x/dualstaking/... | go-junit-report -iocopy -set-exit-code > dualstaking-report.xml  
        go test -v ./x/fixationstore/... | go-junit-report -iocopy -set-exit-code > fixationstore-report.xml  
        go test -v ./x/timerstore/... | go-junit-report -iocopy -set-exit-code > timerstore-report.xml  
        go test -v ./x/downtime/... | go-junit-report -iocopy -set-exit-code > downtime-report.xml  
        go test -v ./x/rewards/... | go-junit-report -iocopy -set-exit-code > rewards-report.xml  
    
    - name: Test Summary
      uses: test-summary/action@v2
      if: always()
      with:
        paths: |
          utils-report.xml
          common-report.xml  
          pairing-report.xml  
          epochstorage-report.xml  
          spec-report.xml  
          conflict-report.xml  
          plans-report.xml  
          projects-report.xml  
          subscription-report.xml  
          dualstaking-report.xml  
          fixationstore-report.xml  
          timerstore-report.xml  
          downtime-report.xml  
          rewards-report.xml  