name: Create a release

on:
  workflow_dispatch:
    inputs:
      rel_version:
        description: 'Release version (examples: v1.3.0-rc.1, v1.3.0)'
        required: true 
        type: string

jobs:
  create-release:
    name: Creates release branch and tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install pcre2-utils
      - name: Create release branch and tag
        env:
          GITHUB_TOKEN: ${{ secrets.LAVANET_BOT_TOKEN }}
        run: |
          git config user.email "bot@lavanet.xyz"
          git config user.name "LavaNet Bot"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          chmod +x ./.github/scripts/create-release.sh
          ./.github/scripts/create-release.sh ${{ inputs.rel_version }}