name: Lava e2e Tests

on: [push, pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    
    # Install Ignite
    - name: ignite install
      run: git clone --depth 1 --branch v0.22.2 https://github.com/ignite/cli && cd cli && make install 
      # run: curl https://get.ignite.com/cli! | bash
    - name: ignite version
      run:  ignite version
    # - name: starport install
    #   run: curl https://get.starport.network/starport@v0.19.2! | bash
    # - name: starport version
    #   run:  starport version

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    # Pre-build with ignite
    - name: ignite build
      run: ignite chain build -v
    # - name: starport build
    #   run: starport chain build -v

    ######################################################
    ### Run lava unitests
    ######################################################
    - name: lava pairing unit Tests
      run: go test ./x/pairing/ ./x/pairing/keeper ./x/pairing/types -v
      
    - name: lava epochstorage unit Tests
      run: go test ./x/epochstorage/ ./x/epochstorage/keeper ./x/epochstorage/types -v

    - name: lava spec unit Tests
      run: go test ./x/spec/ ./x/spec/keeper ./x/spec/types -v

    - name: lava conflict unit Tests
      run: go test ./x/conflict/ ./x/conflict/keeper ./x/conflict/types -v
      
    ######################################################
    ### Run Lava E2E Tests IGNITE VERSION:0.22.1
    ######################################################
    - name: Run Lava E2E Tests IGNITE VERSION:0.22.1 -timeout 1200s
      run: go test ./testutil/e2e/ -v -timeout 1200s # 20mins

    # Show Stake Lava Logs
    - name: cat stakeLava.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/stakeLava.log

    # Show JSONRPC Logs
    - name: cat jsonProxy.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/jsonProxy.log
    - name: cat jsonProvider.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/jsonProvider.log
    - name: cat jsonGateway.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/jsonGateway.log

    # Show REST Logs
    - name: cat restProvider.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/restProvider.log
    - name: cat restGateway.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/restGateway.log

    # Show TENDERMINT Logs
    - name: cat tendermintProvider.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/tendermintProvider.log
    - name: cat tendermintGateway.log
      if: success() || failure()
      run: cat ./testutil/e2e/logs/tendermintGateway.log
    # - name: docker build 
    #   run: docker build -t lava-docker scripts/docker
  
    