name: Lava e2e Tests

on: [push, pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    
    # Install Ignite
    - name: ignite install
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_minutes: 20
        command: git clone --depth 1 --branch v0.22.2 https://github.com/ignite/cli && cd cli && make install 

    - name: ignite version
      run:  ignite version

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    # Pre-build with ignite
    - name: ignite build
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_minutes: 20
        command: ignite chain build -v

    ######################################################
    ### Run lava unitests
    ######################################################
    - name: lava pairing unit Tests
      run: go test ./x/pairing/ ./x/pairing/keeper ./x/pairing/types -v
      
    - name: lava epochstorage unit Tests
      run: go test ./x/epochstorage/ ./x/epochstorage/keeper ./x/epochstorage/types -v

    - name: lava spec unit Tests
      run: go test ./x/spec/ ./x/spec/keeper ./x/spec/types -v

    - name: lava conflict unit Tests
      run: go test ./x/conflict/ ./x/conflict/keeper ./x/conflict/types -v

    ######################################################
    ### Run relayer unitests
    ######################################################
    - name: Run Relayer unit Tests
      run: go test ./relayer/lavasession/ ./protocol/chaintracker/ ./relayer/chainproxy/ -v
    - name: Run Relayer Metrics Unit Tests
      run: go test ./relayer/metrics/  -v

    ######################################################
    ### Run Lava E2E Tests IGNITE VERSION:0.22.1
    ######################################################
    - name: Run Lava E2E Tests IGNITE VERSION:0.22.1 -timeout 1200s
      run: go test ./testutil/e2e/ -v -timeout 1200s # 20mins
      
    - name: Stake Lava All Logs
      if: always()
      run: cat testutil/e2e/logs/01_stakeLava.log

    - name: Stake Lava Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/01_stakeLava_errors.log

    - name: head -n 300 JSON Proxy Logs
      if: always()
      run: head -n 300 testutil/e2e/logs/02_jsonProxy.log

    - name: tail -n 300 JSON Proxy Logs
      if: always()
      run: tail -n 300 testutil/e2e/logs/02_jsonProxy.log

    - name: JSON Proxy Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/02_jsonProxy_errors.log

    - name: JSON Provider All Logs
      if: always()
      run: grep "" testutil/e2e/logs/03_jsonProvider* --exclude="*errors*"

    - name: JSON Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/03_jsonProvider* --include="*errors*"

    - name: JSON Gateway All Logs
      if: always()
      run: cat testutil/e2e/logs/04_jsonGateway.log

    - name: JSON Gateway Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/04_jsonGateway_errors.log

    - name: Tendermint Provider All Logs
      if: always()
      run: grep "" testutil/e2e/logs/05_tendermintProvider* --exclude="*errors*"

    - name: Tendermint Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/05_tendermintProvider* --include="*errors*"

    - name: Tendermint Gateway All Logs
      if: always()
      run: cat testutil/e2e/logs/06_tendermintGateway.log

    - name: Tendermint Gateway Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/06_tendermintGateway_errors.log

    - name: Lava over Lava All Logs
      if: always()
      run: cat testutil/e2e/logs/07_lavaOverLava.log

    - name: Lava over Lava Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/07_lavaOverLava_errors.log

    - name: Rest Provider All Logs
      if: always()
      run: grep "" testutil/e2e/logs/08_restProvider* --exclude="*errors*"

    - name: Rest Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/08_restProvider* --include="*errors*"

    - name: Rest Gateway All Logs
      if: always()
      run: cat testutil/e2e/logs/09_restGateway.log

    - name: Rest Gateway Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/09_restGateway_errors.log
    
    - name: GRPC Provider All Logs
      if: always()
      run: grep "" testutil/e2e/logs/10_grpcProvider* --exclude="*errors*"

    - name: GRPC Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/10_grpcProvider* --include="*errors*"

    - name: GRPC Gateway All Logs
      if: always()
      run: cat testutil/e2e/logs/11_grpcGateway.log

    - name: GRPC Gateway Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/11_grpcGateway_errors.log