name: Lava e2e Tests

on: [push, pull_request]
# on: [push]


jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    # - name: install screen
    #   run: sudo apt install screen -y
    - name: ignite install
      run: curl https://get.ignite.com/cli! | bash
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    # - name: docker build 
    #   run: docker build -t lava-docker .
    - name: ignite version
      run:  ignite version
    - name: starport install
      run: curl https://get.starport.network/starport@v0.19.2! | bash
    - name: starport version
      run:  starport version
    - name: home
      run:  pwd && ls -l
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l
    - name: ignite build
      run: ignite chain build -v
    - name: starport build
      run: starport chain build -v
    
    - name: lava unit Tests
      run: go test ./x/pairing/keeper -v