name: Lava e2e Tests

on: [push, pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    
    # Install Ignite
    - name: ignite install
      run: curl https://get.ignite.com/cli! | bash
    - name: ignite version
      run:  ignite version
    # - name: starport install
    #   run: curl https://get.starport.network/starport@v0.19.2! | bash
    # - name: starport version
    #   run:  starport version

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    # Pre-build with ignite
    - name: ignite build
      run: ignite chain build -v
    # - name: starport build
    #   run: starport chain build -v

    ######################################################
    ### Run Lava E2E Tests IGNITE VERSION:0.22.1
    ######################################################
    - name: Run Lava E2E Tests IGNITE VERSION:0.22.1 -timeout 660s
      run: go test ./testutil/e2e/ -v -timeout 660s # 11mins

    # Show ETH Logs
    - name: cat clientEth.log
      run: cat ./testutil/e2e/logs/clientEth.log
    - name: cat providers_eth.log
      run: cat ./testutil/e2e/logs/providers_eth.log
  
    # Show OSMOSIS Logs
    - name: cat clientOsmo.log
      run: cat ./testutil/e2e/logs/clientOsmo.log
    - name: cat clientOsmo2.log
      run: cat ./testutil/e2e/logs/clientOsmo2.log
    - name: cat providers_osmosis.log
      run: cat ./testutil/e2e/logs/providers_eth.log
    # - name: docker build 
    #   run: docker build -t lava-docker scripts/docker
  
    - name: lava unit Tests
      run: go test ./x/pairing/keeper -v