name: Lava e2e Tests

on: [push, pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    
    # Install Ignite
    - name: ignite install
      run: git clone --depth 1 --branch v0.22.2 https://github.com/ignite/cli && cd cli && make install 
      # run: curl https://get.ignite.com/cli! | bash
    - name: ignite version
      run:  ignite version
    # - name: starport install
    #   run: curl https://get.starport.network/starport@v0.19.2! | bash
    # - name: starport version
    #   run:  starport version

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    # Pre-build with ignite
    - name: ignite build
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_minutes: 20
        command: ignite chain build -v

    ######################################################
    ### Run lava unitests
    ######################################################
    - name: lava pairing unit Tests
      run: go test ./x/pairing/ ./x/pairing/keeper ./x/pairing/types -v
      
    - name: lava epochstorage unit Tests
      run: go test ./x/epochstorage/ ./x/epochstorage/keeper ./x/epochstorage/types -v

    - name: lava spec unit Tests
      run: go test ./x/spec/ ./x/spec/keeper ./x/spec/types -v

    - name: lava conflict unit Tests
      run: go test ./x/conflict/ ./x/conflict/keeper ./x/conflict/types -v

    ######################################################
    ### Run relayer unitests
    ######################################################
    - name: Run Relayer unit Tests
      run: go test ./relayer/lavasession/ ./protocol/chaintracker/ ./relayer/chainproxy/ -v
    - name: Run Relayer Metrics Unit Tests
      run: go test ./relayer/metrics/  -v

    ######################################################
    ### Run Lava E2E Tests IGNITE VERSION:0.22.1
    ######################################################
    - name: Run Lava E2E Tests IGNITE VERSION:0.22.1 -timeout 1200s
      run: go test ./testutil/e2e/ -v -timeout 1200s # 20mins

    - name: Check 01_stakeLava.log
      if: success() || failure()
      id: check_01_stakeLava
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/01_stakeLava.log"

    - name: cat testutil/e2e/logs/01_stakeLava.log
      if: (success() || failure()) && steps.check_01_stakeLava.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/01_stakeLava.log

    - name: Check 01_stakeLava_errors.log
      if: success() || failure()
      id: check_01_stakeLava_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/01_stakeLava_errors.log"

    - name: cat testutil/e2e/logs/01_stakeLava_errors.log
      if: (success() || failure()) && steps.check_01_stakeLava_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/01_stakeLava_errors.log

    - name: Check 02_jsonProxy.log
      if: success() || failure()
      id: check_02_jsonProxy
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/02_jsonProxy.log"

    - name: head -n 300 testutil/e2e/logs/02_jsonProxy.log
      if: (success() || failure()) && steps.check_02_jsonProxy.outputs.files_exists == 'true'
      run: head -n 300 testutil/e2e/logs/02_jsonProxy.log

    - name: tail -n 300 testutil/e2e/logs/02_jsonProxy.log
      if: (success() || failure()) && steps.check_02_jsonProxy.outputs.files_exists == 'true'
      run: tail -n 300 testutil/e2e/logs/02_jsonProxy.log

    - name: Check 02_jsonProxy_errors.log
      if: success() || failure()
      id: check_02_jsonProxy_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/02_jsonProxy_errors.log"

    - name: cat testutil/e2e/logs/02_jsonProxy_errors.log
      if: (success() || failure()) && steps.check_02_jsonProxy_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/02_jsonProxy_errors.log

    - name: Check 03_jsonProvider.log
      if: success() || failure()
      id: check_03_jsonProvider
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/03_jsonProvider.log"

    - name: cat testutil/e2e/logs/03_jsonProvider.log
      if: (success() || failure()) && steps.check_03_jsonProvider.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/03_jsonProvider.log

    - name: Check 03_jsonProvider_errors.log
      if: success() || failure()
      id: check_03_jsonProvider_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/03_jsonProvider_errors.log"

    - name: cat testutil/e2e/logs/03_jsonProvider_errors.log
      if: (success() || failure()) && steps.check_03_jsonProvider_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/03_jsonProvider_errors.log

    - name: Check 04_jsonGateway.log
      if: success() || failure()
      id: check_04_jsonGateway
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/04_jsonGateway.log"

    - name: cat testutil/e2e/logs/04_jsonGateway.log
      if: (success() || failure()) && steps.check_04_jsonGateway.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/04_jsonGateway.log

    - name: Check 04_jsonGateway_errors.log
      if: success() || failure()
      id: check_04_jsonGateway_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/04_jsonGateway_errors.log"

    - name: cat testutil/e2e/logs/04_jsonGateway_errors.log
      if: (success() || failure()) && steps.check_04_jsonGateway_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/04_jsonGateway_errors.log

    - name: Check 05_tendermintProvider.log
      if: success() || failure()
      id: check_05_tendermintProvider
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/05_tendermintProvider.log"

    - name: cat testutil/e2e/logs/05_tendermintProvider.log
      if: (success() || failure()) && steps.check_05_tendermintProvider.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/05_tendermintProvider.log

    - name: Check 05_tendermintProvider_errors.log
      if: success() || failure()
      id: check_05_tendermintProvider_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/05_tendermintProvider_errors.log"

    - name: cat testutil/e2e/logs/05_tendermintProvider_errors.log
      if: (success() || failure()) && steps.check_05_tendermintProvider_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/05_tendermintProvider_errors.log

    - name: Check 06_tendermintGateway.log
      if: success() || failure()
      id: check_06_tendermintGateway
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/06_tendermintGateway.log"

    - name: cat testutil/e2e/logs/06_tendermintGateway.log
      if: (success() || failure()) && steps.check_06_tendermintGateway.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/06_tendermintGateway.log

    - name: Check 06_tendermintGateway_errors.log
      if: success() || failure()
      id: check_06_tendermintGateway_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/06_tendermintGateway_errors.log"

    - name: cat testutil/e2e/logs/06_tendermintGateway_errors.log
      if: (success() || failure()) && steps.check_06_tendermintGateway_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/06_tendermintGateway_errors.log

    - name: Check 07_lavaOverLava.log
      if: success() || failure()
      id: check_07_lavaOverLava
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/07_lavaOverLava.log"

    - name: cat testutil/e2e/logs/07_lavaOverLava.log
      if: (success() || failure()) && steps.check_07_lavaOverLava.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/07_lavaOverLava.log

    - name: Check 07_lavaOverLava_errors.log
      if: success() || failure()
      id: check_07_lavaOverLava_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/07_lavaOverLava_errors.log"

    - name: cat testutil/e2e/logs/07_lavaOverLava_errors.log
      if: (success() || failure()) && steps.check_07_lavaOverLava_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/07_lavaOverLava_errors.log

    - name: Check 08_restProvider.log
      if: success() || failure()
      id: check_08_restProvider
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/08_restProvider.log"

    - name: cat testutil/e2e/logs/08_restProvider.log
      if: (success() || failure()) && steps.check_08_restProvider.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/08_restProvider.log

    - name: Check 08_restProvider_errors.log
      if: success() || failure()
      id: check_08_restProvider_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/08_restProvider_errors.log"

    - name: cat testutil/e2e/logs/08_restProvider_errors.log
      if: (success() || failure()) && steps.check_08_restProvider_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/08_restProvider_errors.log

    - name: Check 09_restGateway.log
      if: success() || failure()
      id: check_09_restGateway
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/09_restGateway.log"

    - name: cat testutil/e2e/logs/09_restGateway.log
      if: (success() || failure()) && steps.check_09_restGateway.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/09_restGateway.log

    - name: Check 09_restGateway_errors.log
      if: success() || failure()
      id: check_09_restGateway_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/09_restGateway_errors.log"

    - name: cat testutil/e2e/logs/09_restGateway_errors.log
      if: (success() || failure()) && steps.check_09_restGateway_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/09_restGateway_errors.log
    
    - name: Check 10_grpcProvider.log
      if: success() || failure()
      id: check_10_grpcProvider
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/10_grpcProvider.log"

    - name: cat testutil/e2e/logs/10_grpcProvider.log
      if: (success() || failure()) && steps.check_10_grpcProvider.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/10_grpcProvider.log

    - name: Check 10_grpcProvider_errors.log
      if: success() || failure()
      id: check_10_grpcProvider_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/10_grpcProvider_errors.log"

    - name: cat testutil/e2e/logs/10_grpcProvider_errors.log
      if: (success() || failure()) && steps.check_10_grpcProvider_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/10_grpcProvider_errors.log

    - name: Check 11_grpcGateway.log
      if: success() || failure()
      id: check_11_grpcGateway
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/11_grpcGateway.log"

    - name: cat testutil/e2e/logs/11_grpcGateway.log
      if: (success() || failure()) && steps.check_11_grpcGateway.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/11_grpcGateway.log

    - name: Check 11_grpcGateway_errors.log
      if: success() || failure()
      id: check_11_grpcGateway_errors
      uses: andstor/file-existence-action@v2
      with:
        files: "testutil/e2e/logs/11_grpcGateway_errors.log"

    - name: cat testutil/e2e/logs/11_grpcGateway_errors.log
      if: (success() || failure()) && steps.check_11_grpcGateway_errors.outputs.files_exists == 'true'
      run: cat testutil/e2e/logs/11_grpcGateway_errors.log