name: Lava E2E Tests

on: [pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    
    # Install Ignite
    - name: ignite install
      run: git clone --depth 1 --branch v0.22.2 https://github.com/ignite/cli && cd cli && make install 
      # run: curl https://get.ignite.com/cli! | bash
    - name: ignite version
      run:  ignite version
    # - name: starport install
    #   run: curl https://get.starport.network/starport@v0.19.2! | bash
    # - name: starport version
    #   run:  starport version

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    # Pre-build with ignite
    - name: ignite build
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_minutes: 20
        command: ignite chain build -v

      # Install Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 20

      # Install dependencies and build
    - name: Install dependencies and build
      run: |
        cd ecosystem/lava-sdk
        npm install
        npm run build

    ######################################################
    ### Run Lava E2E Tests IGNITE VERSION:0.22.1
    ######################################################
    - name: Run Lava E2E Tests IGNITE VERSION:0.22.1 -timeout 1200s
      run: go test ./testutil/e2e/ -v -timeout 1200s # 20mins
      
    - name: Stake Lava All Logs
      if: always()
      run: cat testutil/e2e/logs/01_stakeLava.log

    - name: Stake Lava Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/01_stakeLava_errors.log

    - name: head -n 300 JSON Proxy Logs
      if: always()
      run: head -n 300 testutil/e2e/logs/02_jsonProxy.log

    - name: tail -n 300 JSON Proxy Logs
      if: always()
      run: tail -n 300 testutil/e2e/logs/02_jsonProxy.log

    - name: JSON Proxy Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/02_jsonProxy_errors.log

    - name: JSON Provider All Logs
      if: always()
      run: grep "" testutil/e2e/logs/03_EthProvider* --exclude="*errors*"

    - name: JSON Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/03_EthProvider* --include="*errors*"

    - name: JSON Consumer All Logs
      if: always()
      run: grep "" testutil/e2e/logs/04_jsonConsumer* --exclude="*errors*"

    - name: JSON Consumer Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/04_jsonConsumer* --include="*errors*"

    - name: Lava Provider All Logs
      if: always()
      run: grep "" testutil/e2e/logs/05_LavaProvider* --exclude="*errors*"

    - name: Lava Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/05_LavaProvider* --include="*errors*"

    - name: Lava over Lava All Logs
      if: always()
      run: cat testutil/e2e/logs/07_lavaOverLava.log

    - name: Lava over Lava Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/logs/07_lavaOverLava_errors.log

    - name: RPCConsumer Consumer All Logs
      if: always()
      run: grep "" testutil/e2e/logs/06_RPCConsumer* --exclude="*errors*"

    - name: RPCConsumer Consumer Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/logs/06_RPCConsumer* --include="*errors*"
