name: Lava e2e Tests

# on: [push, pull_request]
on: [push]


jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    # - name: install screen
    #   run: sudo apt install screen -y
    - name: ignite install
      run: curl https://get.ignite.com/cli! | bash
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    # - name: docker build 
    #   run: docker build -t lava-docker .
    - name: ignite version
      run:  ignite version
    - name: starport install
      run: curl https://get.starport.network/starport@v0.19.2! | bash
    - name: starport version
      run:  starport version
    - name: home
      run:  pwd && ls -l
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l
    - name: ignite build
      run: ignite chain build -v
    - name: starport build
      run: starport chain build -v
    
    
    # - name: node
    #   run: cd ~/go/lava; starport chain serve -v -r
    # - name: test timeout 3 mins
      run: cd ~/go/lava; go test ./testutil/e2e/ -v
      run: go test -timeout 180s
    - name: lava e2e tests
      # run: cd ~/go/lava; go test ./testutil/e2e/ -v
      run: go test ./testutil/e2e/ -v &

    - name: check lavad prov1 output
      run: sleep 120 ; go run relayer/cmd/relayer/main.go server 127.0.0.1 2221 ws://kololo8ex9:ifififkwqlspAFJIjfdMCsdmasdgAKoakdFOAKSFOakfaSEFkbntb311esad@168.119.211.250/eth/ws/ ETH1 jsonrpc --from servicer1
    
    # - name: cat provX.log
    #   run: cat ./testutil/e2e/logs/provX.log

    - name: cat client.log
      run: cat ./testutil/e2e/logs/client.log

  