name: Go Test1

# on: [push, pull_request]
on: [push]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    - name: ignite install
      run: curl https://get.ignite.com/cli! | bash
    - name: starport install
      run: curl https://get.starport.network/starport@v0.19.2! | bash
    - name: starport version
      run:  starport version
    - name: home
      run:  pwd && ls -l
    - name: export gopath
      run:  export GOPATH=/home/runner/work/:$GOPATH
    - name: go env
      run:  go env
    # - name: PATH
    #   run:  export PATH=$PATH:`pwd`:
    - name: node
      run: echo pwd; starport chain serve -v -r
    - name: test
      run: go test ./testutil/e2e/ -v

  