name: Lava SDK Tests

on: 
  pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - uses: actions/setup-go@v5
        with:
          go-version: "1.20.5"

      - uses: actions/setup-node@v4
        with:
          node-version: "21.2.0"

      - name: Init the SDK
        run: GOPATH=~/go ./scripts/init_sdk.sh -s
        working-directory: ./ecosystem/lava-sdk

      - name: ESLint
        run: ./node_modules/.bin/eslint '**/*.ts'
        working-directory: ./ecosystem/lava-sdk

      - name: Test
        run: ./node_modules/.bin/jest ./src --ci --reporters=default --reporters=jest-junit
        working-directory: ./ecosystem/lava-sdk

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Lava SDK Tests            
          path: ./ecosystem/lava-sdk/src/*.xml
          reporter: jest-junit  
