name: Lava SDK Tests

on: [pull_request]

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.yarn
                  key: yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: yarn-

            - name: Install modules
              run: yarn install
              working-directory: ./ecosystem/lava-sdk

            - name: ESLint
              run: ./node_modules/.bin/eslint '**/*.ts'
              working-directory: ./ecosystem/lava-sdk

            - name: Test
              run: ./node_modules/.bin/jest ./src
              working-directory: ./ecosystem/lava-sdk
