name: Lava Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
        binary: [lavad, lavap, lavavisor]
        include:
          - targetos: darwin
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Download Dependencies
        run: go mod download

      - name: Build ${{ matrix.binary }}
        run: |
          GOWRK=off go build cmd/${{ matrix.binary }}/main.go
      
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.binary }}-${{ matrix.targetos }}-${{ matrix.arch }}
      #     path: dist/**/*