name: Lava SDK Tests

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.5"

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install protoc executable
        run: sudo apt update && sudo apt install -y protobuf-compiler

      - name: Install yarn and protoc-gen-ts
        run: npm install -g yarn protoc-gen-ts

      - name: Run go mod tidy
        run: go mod tidy

      - name: Install modules
        run: yarn install
        working-directory: ./ecosystem/lava-sdk

      - name: Prepare proto files
        run: GOPATH=~/go ./scripts/protoc_grpc_relay.sh
        working-directory: ./ecosystem/lava-sdk

      - name: ESLint
        run: ./node_modules/.bin/eslint '**/*.ts'
        working-directory: ./ecosystem/lava-sdk

      - name: Test
        run: ./node_modules/.bin/jest ./src
        working-directory: ./ecosystem/lava-sdk
