name: Lava Protocol Tests

on: 
  pull_request

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.20.5

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/:$GOPATH/bin
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    ######################################################
    ### Run protocol unitests
    ######################################################
    - name: Run Lava Tests
      run: |
        go install github.com/jstemmer/go-junit-report/v2@latest
        go test -v ./protocol/... | go-junit-report -iocopy -set-exit-code -out protocol-report.xml  
        go test -v ./ecosystem/cache/... | go-junit-report -iocopy -set-exit-code -out cache-report.xml
    - name: Test Summary
      uses: test-summary/action@v2
      if: always()
      with:
        paths: |
          protocol-report.xml     
          cache-report.xml